### ISSUE TITLE
How to replace Godard footer with mine

### ISSUE THREAD

**Issue by lyonsden10** [godaddy/wp-primer-theme#153] opened 2017-02-08 15:34 UTC
Can someone please let me know what code to put into the custom css to eliminate the GoDaddy  footer and replace  with my own information?  Thanks,  susan

**Comment by EvanHerman** [comment] 2017-02-10 22:03
Hi @lyonsden10 ,

I am going to close this one since it appears to be a duplicate of the other open issue (#154).

**Closed as completed by EvanHerman** 2017-02-10 22:03 UTC
Labels: duplicate
