### ISSUE TITLE
Images don´t open in lightbox window

### ISSUE THREAD

**Issue by JoanMorci** [godaddy/wp-primer-theme#208] opened 2017-05-21 12:59 UTC
Hello @EvanHerman !

This theme has many interesting options, but **I don´t see in any site the option of activating some type ‘lightbox window’**, to open the images in the same site.

Is the option hidden somewhere? And if it isn´t… do you plan to include this option in any new version of the theme?

Or… do you recommend including it with a plugin? I would prefer that it be integrated into the options panel of the theme.

Greetings!

**Comment by frankiejarrett** [comment] 2017-05-23 21:28
Duplicate of https://wordpress.org/support/topic/images-dont-open-in-lightbox-window/

**Closed as completed by frankiejarrett** 2017-05-23 21:28 UTC
Labels: question
