### ISSUE TITLE
Menu behaves strangely at some page widths

### ISSUE THREAD

**Issue by TessLew15** [godaddy/wp-primer-theme#262] opened 2018-07-20 04:04 UTC
When there is a second level dropdown menu that appears to the right of the parent dropdown menu, at some page widths it will not respond to being clicked. Instead, it will briefly jump to the left of the parent dropdown menu before closing. The link will only work if the menu is opened a second time and the same link clicked again.

For example, this link will not work when clicked the first time:
![screen shot 2018-07-13 at 3 20 50 pm](https://user-images.githubusercontent.com/41460418/42982597-3db57fce-8c25-11e8-9f83-c75e3a80375a.png)

This is a problem with the JQuery. If JS is disabled on the browser, the pure CSS menu will work fine.

This is using Opera 54.0 on a Mac

**Comment by EvanHerman** [comment] 2018-07-20 13:26
Hi @TessLew15 

I'd be happy to take a look and see if that's something I can reproduce. I believe the menu is jumping to the left of the parent menu due to the page width, and having it on the left would overflow beyond the width of the browser window. Although, the menu should still work on the left vs right side.

Do you happen to have a link to that page where I can take a look? I'll do some testing locally and see if I can setup a test instance that replicates the issue.

Evan

**Comment by EvanHerman** [comment] 2018-07-20 22:36
@TessLew15 I was able to locate the bug and come up with a patch for this. We are working on a new release, which will include the fix for this bug. Thank you for reporting the bug here.

Evan

**Closed as completed** 2018-07-26 14:26 UTC

**Comment by TessLew15** [comment] 2018-08-23 02:28
Thanks so much Evan!!

**Comment by EvanHerman** [comment] 2018-08-23 04:09
No problem, have a great week!

**Comment by TessLew15** [comment] 2018-08-23 04:16
You too!
